apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    run: nodeapp
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 81
  type: NodePort
  selector:
    run: nodeapp

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nodeapp
    spec:
      containers:
      - name: myapi
        image: index.docker.io/pmoralof/appvisual:latest
        ports:
        - containerPort: 3000
